### ISSUE TITLE
tf3ds wrongly updated by serial_chain.forward_kinematics

### ISSUE THREAD

**Issue by Smilels** [jianglongye/cgf#1]
HI, Jianglong.
When I recently tested pytorch_kinematics with the FK function, I found a bug in your code.
In cgf/robotics.py, line 87, tf3ds is updated every time when the FK is calculated.
tf3ds.update(serial_chain.forward_kinematics(qpos[:, start : start + joint_num], end_only=False))

In this way, even though the input joint angles are only qpos[:, start : start + joint_num], the output of serial_chain.forward_kinematics is still the positions of all links.
For example, when start = 4, instead of positions of  'link_4.0', 'link_5.0', 'link_6.0', 'link_7.0', 'link_7.0_tip' in tf3ds are updated, the calculated positions in tf3ds of 'link_0.0', 'link_1.0', 'link_2.0', 'link_3.0', 'link_3.0_tip' are wrongly overwritten.

I think,  the link positions in tf3ds should only be updated when the corresponding joint angles are given.

 ```
        joint_start = 0
        joint_num = 4
        link_start = 1
        link_num = 5
        for _, serial_chain in enumerate(self.serial_chains):
            ret = serial_chain.forward_kinematics(robot_joint_angles[:, joint_start : joint_start + joint_num], end_only=False)
            for link in self.link_names[link_start: link_start + 5]:
                     tf3ds.update({link: ret[link]})            
            joint_start += joint_num
            link_start += link_num
```

**Comment by jianglongye** [comment]
Thank you for your interest in this project. After reviewing the code snippet you mentioned, I notices this bug as well. The issue stems from the fact that in the later versions of pytorch_kinematics (e.g., 0.6.1), the `serial_chain` returns all links across all chains, rather than just the links in the specified serial chain.

I also noticed that the recent versions of pytorch_kinematics now support kinematic chains with **multiple end effectors**, which wasn't the case when we initially developed `cgf`. Therefore, I updated the code to use `chain` instead of `serial_chain`. The issue is now resolved, and the running speed has improved. (10 mins -> 4 mins).

commit: 4b9ba1682bfef6e40824849947bf9f91e0882e4e

![image](https://github.com/user-attachments/assets/a7f656bd-3b1d-493c-9785-a4b4b9ea7c91)
